/* ═══════════════════════════════════════════
   기호 사전 · 팔레트 공용 데이터
   cat  : 분류
   code : 삽입될 KaTeX 코드 (▢ 는 입력 자리)
   desc : 한국어 설명
   easy : 빠른 입력 모드에서 쓸 수 있는 표기 (없으면 생략)
   ═══════════════════════════════════════════ */
const REF = [
  /* ── 기본 구조 ── */
  {cat:'기본', code:'\\frac{▢}{▢}', desc:'분수', easy:'a/b', tex:'\\frac{a}{b}'},
  {cat:'기본', code:'\\dfrac{▢}{▢}', desc:'큰 분수 (본문에서도 크게)', tex:'\\dfrac{a}{b}'},
  {cat:'기본', code:'\\tfrac{▢}{▢}', desc:'작은 분수', tex:'\\tfrac{a}{b}'},
  {cat:'기본', code:'^{▢}', desc:'위 첨자 (거듭제곱)', easy:'x^2', tex:'x^{2}'},
  {cat:'기본', code:'_{▢}', desc:'아래 첨자', easy:'a_1', tex:'a_{1}'},
  {cat:'기본', code:'\\sqrt{▢}', desc:'제곱근', easy:'sqrt(x)', tex:'\\sqrt{x}'},
  {cat:'기본', code:'\\sqrt[▢]{▢}', desc:'n제곱근', easy:'root(3)(x)', tex:'\\sqrt[3]{x}'},
  {cat:'기본', code:'\\binom{▢}{▢}', desc:'이항계수 (조합 nCr)', easy:'binom(n,k)', tex:'\\binom{n}{k}'},
  {cat:'기본', code:'\\overline{▢}', desc:'윗줄 (평균·켤레)', easy:'bar(x)', tex:'\\overline{x}'},
  {cat:'기본', code:'\\underline{▢}', desc:'밑줄', tex:'\\underline{x}'},
  {cat:'기본', code:'\\text{▢}', desc:'일반 글자 (한글·문장)', easy:'"글자"', tex:'\\text{글자}'},

  /* ── 연산 ── */
  {cat:'연산', code:'+', desc:'더하기', tex:'+'},
  {cat:'연산', code:'-', desc:'빼기', tex:'-'},
  {cat:'연산', code:'\\times', desc:'곱하기 ×', easy:'xx', tex:'\\times'},
  {cat:'연산', code:'\\div', desc:'나누기 ÷', easy:'-:', tex:'\\div'},
  {cat:'연산', code:'\\cdot', desc:'가운뎃점 곱', easy:'*', tex:'\\cdot'},
  {cat:'연산', code:'\\pm', desc:'플러스마이너스 ±', easy:'+-', tex:'\\pm'},
  {cat:'연산', code:'\\mp', desc:'마이너스플러스 ∓', easy:'-+', tex:'\\mp'},
  {cat:'연산', code:'\\ast', desc:'별표 ∗', tex:'\\ast'},
  {cat:'연산', code:'\\circ', desc:'합성 ∘', tex:'\\circ'},
  {cat:'연산', code:'\\oplus', desc:'직합 ⊕', tex:'\\oplus'},
  {cat:'연산', code:'\\otimes', desc:'텐서곱 ⊗', tex:'\\otimes'},
  {cat:'연산', code:'\\%', desc:'퍼센트', tex:'\\%'},
  {cat:'연산', code:'^{\\circ}', desc:'도 (각도)', easy:'deg', tex:'90^{\\circ}'},

  /* ── 관계 ── */
  {cat:'관계', code:'=', desc:'같다', tex:'='},
  {cat:'관계', code:'\\ne', desc:'같지 않다 ≠', easy:'!=', tex:'\\ne'},
  {cat:'관계', code:'\\lt', desc:'작다 <', tex:'\\lt'},
  {cat:'관계', code:'\\gt', desc:'크다 >', tex:'\\gt'},
  {cat:'관계', code:'\\le', desc:'작거나 같다 ≤', easy:'<=', tex:'\\le'},
  {cat:'관계', code:'\\ge', desc:'크거나 같다 ≥', easy:'>=', tex:'\\ge'},
  {cat:'관계', code:'\\approx', desc:'근사 ≈', easy:'~=', tex:'\\approx'},
  {cat:'관계', code:'\\equiv', desc:'합동·항등 ≡', tex:'\\equiv'},
  {cat:'관계', code:'\\sim', desc:'닮음 ∼', tex:'\\sim'},
  {cat:'관계', code:'\\cong', desc:'합동 ≅', tex:'\\cong'},
  {cat:'관계', code:'\\propto', desc:'비례 ∝', tex:'\\propto'},
  {cat:'관계', code:'\\ll', desc:'매우 작다 ≪', tex:'\\ll'},
  {cat:'관계', code:'\\gg', desc:'매우 크다 ≫', tex:'\\gg'},
  {cat:'관계', code:'\\doteq', desc:'거의 같다 ≐', tex:'\\doteq'},

  /* ── 그리스 소문자 ── */
  {cat:'그리스', code:'\\alpha', desc:'알파', easy:'alpha', tex:'\\alpha'},
  {cat:'그리스', code:'\\beta', desc:'베타', easy:'beta', tex:'\\beta'},
  {cat:'그리스', code:'\\gamma', desc:'감마', easy:'gamma', tex:'\\gamma'},
  {cat:'그리스', code:'\\delta', desc:'델타', easy:'delta', tex:'\\delta'},
  {cat:'그리스', code:'\\epsilon', desc:'엡실론', easy:'epsilon', tex:'\\epsilon'},
  {cat:'그리스', code:'\\varepsilon', desc:'엡실론(변형)', tex:'\\varepsilon'},
  {cat:'그리스', code:'\\zeta', desc:'제타', easy:'zeta', tex:'\\zeta'},
  {cat:'그리스', code:'\\eta', desc:'에타', easy:'eta', tex:'\\eta'},
  {cat:'그리스', code:'\\theta', desc:'세타', easy:'theta', tex:'\\theta'},
  {cat:'그리스', code:'\\vartheta', desc:'세타(변형)', tex:'\\vartheta'},
  {cat:'그리스', code:'\\iota', desc:'요타', easy:'iota', tex:'\\iota'},
  {cat:'그리스', code:'\\kappa', desc:'카파', easy:'kappa', tex:'\\kappa'},
  {cat:'그리스', code:'\\lambda', desc:'람다', easy:'lambda', tex:'\\lambda'},
  {cat:'그리스', code:'\\mu', desc:'뮤 (평균)', easy:'mu', tex:'\\mu'},
  {cat:'그리스', code:'\\nu', desc:'뉴', easy:'nu', tex:'\\nu'},
  {cat:'그리스', code:'\\xi', desc:'크시', easy:'xi', tex:'\\xi'},
  {cat:'그리스', code:'\\pi', desc:'파이', easy:'pi', tex:'\\pi'},
  {cat:'그리스', code:'\\rho', desc:'로', easy:'rho', tex:'\\rho'},
  {cat:'그리스', code:'\\sigma', desc:'시그마 (표준편차)', easy:'sigma', tex:'\\sigma'},
  {cat:'그리스', code:'\\tau', desc:'타우', easy:'tau', tex:'\\tau'},
  {cat:'그리스', code:'\\upsilon', desc:'입실론', tex:'\\upsilon'},
  {cat:'그리스', code:'\\phi', desc:'파이(피)', easy:'phi', tex:'\\phi'},
  {cat:'그리스', code:'\\varphi', desc:'피(변형)', tex:'\\varphi'},
  {cat:'그리스', code:'\\chi', desc:'카이', easy:'chi', tex:'\\chi'},
  {cat:'그리스', code:'\\psi', desc:'프시', easy:'psi', tex:'\\psi'},
  {cat:'그리스', code:'\\omega', desc:'오메가', easy:'omega', tex:'\\omega'},
  {cat:'그리스', code:'\\Gamma', desc:'대문자 감마', easy:'Gamma', tex:'\\Gamma'},
  {cat:'그리스', code:'\\Delta', desc:'대문자 델타 (변화량)', easy:'Delta', tex:'\\Delta'},
  {cat:'그리스', code:'\\Theta', desc:'대문자 세타', easy:'Theta', tex:'\\Theta'},
  {cat:'그리스', code:'\\Lambda', desc:'대문자 람다', easy:'Lambda', tex:'\\Lambda'},
  {cat:'그리스', code:'\\Xi', desc:'대문자 크시', tex:'\\Xi'},
  {cat:'그리스', code:'\\Pi', desc:'대문자 파이', easy:'Pi', tex:'\\Pi'},
  {cat:'그리스', code:'\\Sigma', desc:'대문자 시그마', easy:'Sigma', tex:'\\Sigma'},
  {cat:'그리스', code:'\\Phi', desc:'대문자 피', easy:'Phi', tex:'\\Phi'},
  {cat:'그리스', code:'\\Psi', desc:'대문자 프시', tex:'\\Psi'},
  {cat:'그리스', code:'\\Omega', desc:'대문자 오메가 (옴)', easy:'Omega', tex:'\\Omega'},

  /* ── 큰 연산자 ── */
  {cat:'큰기호', code:'\\sum_{▢}^{▢}', desc:'시그마 (합)', easy:'sum_(k=1)^n', tex:'\\sum_{k=1}^{n}'},
  {cat:'큰기호', code:'\\prod_{▢}^{▢}', desc:'파이 (곱)', easy:'prod_(i=1)^n', tex:'\\prod_{i=1}^{n}'},
  {cat:'큰기호', code:'\\int_{▢}^{▢}', desc:'정적분', easy:'int_0^1', tex:'\\int_{0}^{1}'},
  {cat:'큰기호', code:'\\int', desc:'부정적분', easy:'int', tex:'\\int'},
  {cat:'큰기호', code:'\\iint', desc:'이중적분', tex:'\\iint'},
  {cat:'큰기호', code:'\\iiint', desc:'삼중적분', tex:'\\iiint'},
  {cat:'큰기호', code:'\\oint', desc:'선적분 (닫힌 경로)', easy:'oint', tex:'\\oint'},
  {cat:'큰기호', code:'\\lim_{▢}', desc:'극한', easy:'lim_(x->0)', tex:'\\lim_{x \\to 0}'},
  {cat:'큰기호', code:'\\bigcup_{▢}^{▢}', desc:'합집합 (큰)', tex:'\\bigcup_{i=1}^{n}'},
  {cat:'큰기호', code:'\\bigcap_{▢}^{▢}', desc:'교집합 (큰)', tex:'\\bigcap_{i=1}^{n}'},
  {cat:'큰기호', code:'\\max_{▢}', desc:'최댓값', easy:'max', tex:'\\max'},
  {cat:'큰기호', code:'\\min_{▢}', desc:'최솟값', easy:'min', tex:'\\min'},

  /* ── 화살표 ── */
  {cat:'화살표', code:'\\to', desc:'→ (수렴·사상)', easy:'->', tex:'\\to'},
  {cat:'화살표', code:'\\gets', desc:'← (대입)', easy:'<-', tex:'\\gets'},
  {cat:'화살표', code:'\\leftrightarrow', desc:'↔', easy:'<->', tex:'\\leftrightarrow'},
  {cat:'화살표', code:'\\Rightarrow', desc:'⇒ (따라서)', easy:'=>', tex:'\\Rightarrow'},
  {cat:'화살표', code:'\\Leftarrow', desc:'⇐', tex:'\\Leftarrow'},
  {cat:'화살표', code:'\\Leftrightarrow', desc:'⇔ (필요충분)', easy:'<=>', tex:'\\Leftrightarrow'},
  {cat:'화살표', code:'\\mapsto', desc:'↦ (대응)', easy:'|->', tex:'\\mapsto'},
  {cat:'화살표', code:'\\longrightarrow', desc:'긴 →', tex:'\\longrightarrow'},
  {cat:'화살표', code:'\\uparrow', desc:'↑', tex:'\\uparrow'},
  {cat:'화살표', code:'\\downarrow', desc:'↓', tex:'\\downarrow'},
  {cat:'화살표', code:'\\xrightarrow{▢}', desc:'글자 붙은 화살표', tex:'\\xrightarrow{f}'},

  /* ── 집합·논리 ── */
  {cat:'집합', code:'\\in', desc:'∈ 원소이다', easy:'in', tex:'\\in'},
  {cat:'집합', code:'\\notin', desc:'∉ 원소가 아니다', easy:'notin', tex:'\\notin'},
  {cat:'집합', code:'\\subset', desc:'⊂ 부분집합', easy:'sub', tex:'\\subset'},
  {cat:'집합', code:'\\subseteq', desc:'⊆ 부분집합(같아도 됨)', easy:'sube', tex:'\\subseteq'},
  {cat:'집합', code:'\\supset', desc:'⊃', tex:'\\supset'},
  {cat:'집합', code:'\\cup', desc:'∪ 합집합', easy:'uu', tex:'\\cup'},
  {cat:'집합', code:'\\cap', desc:'∩ 교집합', easy:'nn', tex:'\\cap'},
  {cat:'집합', code:'\\setminus', desc:'∖ 차집합', tex:'\\setminus'},
  {cat:'집합', code:'\\emptyset', desc:'∅ 공집합', easy:'empty', tex:'\\emptyset'},
  {cat:'집합', code:'\\forall', desc:'∀ 모든', easy:'AA', tex:'\\forall'},
  {cat:'집합', code:'\\exists', desc:'∃ 존재한다', easy:'EE', tex:'\\exists'},
  {cat:'집합', code:'\\nexists', desc:'∄ 존재하지 않는다', tex:'\\nexists'},
  {cat:'집합', code:'\\neg', desc:'¬ 부정', easy:'not', tex:'\\neg'},
  {cat:'집합', code:'\\land', desc:'∧ 그리고', easy:'and', tex:'\\land'},
  {cat:'집합', code:'\\lor', desc:'∨ 또는', easy:'or', tex:'\\lor'},
  {cat:'집합', code:'\\therefore', desc:'∴ 그러므로', tex:'\\therefore'},
  {cat:'집합', code:'\\because', desc:'∵ 왜냐하면', tex:'\\because'},
  {cat:'집합', code:'\\mathbb{R}', desc:'실수 집합 ℝ', easy:'RR', tex:'\\mathbb{R}'},
  {cat:'집합', code:'\\mathbb{N}', desc:'자연수 집합 ℕ', easy:'NN', tex:'\\mathbb{N}'},
  {cat:'집합', code:'\\mathbb{Z}', desc:'정수 집합 ℤ', easy:'ZZ', tex:'\\mathbb{Z}'},
  {cat:'집합', code:'\\mathbb{Q}', desc:'유리수 집합 ℚ', easy:'QQ', tex:'\\mathbb{Q}'},
  {cat:'집합', code:'\\mathbb{C}', desc:'복소수 집합 ℂ', easy:'CC', tex:'\\mathbb{C}'},

  /* ── 괄호 ── */
  {cat:'괄호', code:'\\left( ▢ \\right)', desc:'자동 크기 소괄호', tex:'\\left(\\frac{a}{b}\\right)'},
  {cat:'괄호', code:'\\left[ ▢ \\right]', desc:'자동 크기 대괄호', tex:'\\left[\\frac{a}{b}\\right]'},
  {cat:'괄호', code:'\\left\\{ ▢ \\right\\}', desc:'중괄호 (보이는 것)', tex:'\\left\\{\\frac{a}{b}\\right\\}'},
  {cat:'괄호', code:'\\left| ▢ \\right|', desc:'절댓값', easy:'abs(x)', tex:'\\left|x\\right|'},
  {cat:'괄호', code:'\\left\\| ▢ \\right\\|', desc:'노름 (벡터 크기)', easy:'norm(v)', tex:'\\left\\|v\\right\\|'},
  {cat:'괄호', code:'\\langle ▢ \\rangle', desc:'⟨ ⟩ 내적·평균', tex:'\\langle a,b \\rangle'},
  {cat:'괄호', code:'\\lfloor ▢ \\rfloor', desc:'⌊ ⌋ 버림 (바닥)', easy:'floor(x)', tex:'\\lfloor x \\rfloor'},
  {cat:'괄호', code:'\\lceil ▢ \\rceil', desc:'⌈ ⌉ 올림 (천장)', easy:'ceil(x)', tex:'\\lceil x \\rceil'},

  /* ── 함수 ── */
  {cat:'함수', code:'\\sin', desc:'사인', easy:'sin', tex:'\\sin'},
  {cat:'함수', code:'\\cos', desc:'코사인', easy:'cos', tex:'\\cos'},
  {cat:'함수', code:'\\tan', desc:'탄젠트', easy:'tan', tex:'\\tan'},
  {cat:'함수', code:'\\csc', desc:'코시컨트', tex:'\\csc'},
  {cat:'함수', code:'\\sec', desc:'시컨트', tex:'\\sec'},
  {cat:'함수', code:'\\cot', desc:'코탄젠트', tex:'\\cot'},
  {cat:'함수', code:'\\arcsin', desc:'역사인', tex:'\\arcsin'},
  {cat:'함수', code:'\\sinh', desc:'쌍곡사인', tex:'\\sinh'},
  {cat:'함수', code:'\\log', desc:'로그', easy:'log', tex:'\\log'},
  {cat:'함수', code:'\\log_{▢}', desc:'밑이 있는 로그', easy:'log_2', tex:'\\log_{2}'},
  {cat:'함수', code:'\\ln', desc:'자연로그', easy:'ln', tex:'\\ln'},
  {cat:'함수', code:'\\exp', desc:'지수함수', easy:'exp', tex:'\\exp'},
  {cat:'함수', code:'\\gcd', desc:'최대공약수', easy:'gcd', tex:'\\gcd'},
  {cat:'함수', code:'\\det', desc:'행렬식', easy:'det', tex:'\\det'},
  {cat:'함수', code:'\\deg', desc:'차수', tex:'\\deg'},
  {cat:'함수', code:'\\dim', desc:'차원', tex:'\\dim'},
  {cat:'함수', code:'\\ker', desc:'핵 (kernel)', tex:'\\ker'},

  /* ── 미적분·물리 ── */
  {cat:'미적분', code:'\\frac{d▢}{d▢}', desc:'도함수', easy:'d/dx', tex:'\\frac{dy}{dx}'},
  {cat:'미적분', code:'\\frac{\\partial ▢}{\\partial ▢}', desc:'편도함수', easy:'del/delx', tex:'\\frac{\\partial f}{\\partial x}'},
  {cat:'미적분', code:'\\frac{d^{2}▢}{d▢^{2}}', desc:'이계도함수', tex:'\\frac{d^{2}y}{dx^{2}}'},
  {cat:'미적분', code:'\\partial', desc:'∂ 편미분 기호', easy:'del', tex:'\\partial'},
  {cat:'미적분', code:'\\nabla', desc:'∇ 나블라 (기울기)', easy:'grad', tex:'\\nabla'},
  {cat:'미적분', code:'\\infty', desc:'∞ 무한대', easy:'oo', tex:'\\infty'},
  {cat:'미적분', code:'\\,d▢', desc:'적분 변수 (앞에 얇은 공백)', easy:'dx', tex:'\\,dx'},
  {cat:'미적분', code:"▢'", desc:'프라임 (미분)', tex:"f'(x)"},
  {cat:'미적분', code:'\\dot{▢}', desc:'시간 미분 (점 하나)', easy:'dot(x)', tex:'\\dot{x}'},
  {cat:'미적분', code:'\\ddot{▢}', desc:'2계 시간 미분', tex:'\\ddot{x}'},

  /* ── 악센트·벡터 ── */
  {cat:'악센트', code:'\\vec{▢}', desc:'벡터 화살표', easy:'vec(v)', tex:'\\vec{v}'},
  {cat:'악센트', code:'\\overrightarrow{▢}', desc:'긴 벡터 화살표', tex:'\\overrightarrow{AB}'},
  {cat:'악센트', code:'\\hat{▢}', desc:'모자 (추정량·단위벡터)', easy:'hat(x)', tex:'\\hat{x}'},
  {cat:'악센트', code:'\\bar{▢}', desc:'바 (평균)', easy:'bar(x)', tex:'\\bar{x}'},
  {cat:'악센트', code:'\\tilde{▢}', desc:'물결', easy:'tilde(x)', tex:'\\tilde{x}'},
  {cat:'악센트', code:'\\widehat{▢}', desc:'넓은 모자', tex:'\\widehat{ABC}'},
  {cat:'악센트', code:'\\overbrace{▢}^{▢}', desc:'위 중괄호 묶음', tex:'\\overbrace{a+b}^{n}'},
  {cat:'악센트', code:'\\underbrace{▢}_{▢}', desc:'아래 중괄호 묶음', tex:'\\underbrace{a+b}_{n}'},

  /* ── 행렬 ── */
  {cat:'행렬', code:'\\begin{pmatrix} ▢ & ▢ \\\\ ▢ & ▢ \\end{pmatrix}', desc:'( ) 행렬', easy:'mat(1,2;3,4)', tex:'\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}'},
  {cat:'행렬', code:'\\begin{bmatrix} ▢ & ▢ \\\\ ▢ & ▢ \\end{bmatrix}', desc:'[ ] 행렬', easy:'bmat(1,2;3,4)', tex:'\\begin{bmatrix}a&b\\\\c&d\\end{bmatrix}'},
  {cat:'행렬', code:'\\begin{vmatrix} ▢ & ▢ \\\\ ▢ & ▢ \\end{vmatrix}', desc:'| | 행렬식', easy:'vmat(1,2;3,4)', tex:'\\begin{vmatrix}a&b\\\\c&d\\end{vmatrix}'},
  {cat:'행렬', code:'\\begin{cases} ▢ & ▢ \\\\ ▢ & ▢ \\end{cases}', desc:'경우 나누기', easy:'cases(x,x>0; -x,x<0)', tex:'\\begin{cases}x & x>0\\\\-x & x<0\\end{cases}'},
  {cat:'행렬', code:'\\cdots', desc:'가로 점 ⋯', tex:'\\cdots'},
  {cat:'행렬', code:'\\vdots', desc:'세로 점 ⋮', tex:'\\vdots'},
  {cat:'행렬', code:'\\ddots', desc:'대각 점 ⋱', tex:'\\ddots'},
  {cat:'행렬', code:'\\ldots', desc:'아래 점 …', tex:'\\ldots'},

  /* ── 통계·확률 ── */
  {cat:'통계', code:'\\bar{x}', desc:'표본평균', tex:'\\bar{x}'},
  {cat:'통계', code:'\\hat{p}', desc:'표본비율 추정량', tex:'\\hat{p}'},
  {cat:'통계', code:'P(▢)', desc:'확률', tex:'P(A)'},
  {cat:'통계', code:'P(▢ \\mid ▢)', desc:'조건부 확률', tex:'P(A \\mid B)'},
  {cat:'통계', code:'E[▢]', desc:'기댓값', tex:'E[X]'},
  {cat:'통계', code:'\\operatorname{Var}(▢)', desc:'분산', tex:'\\operatorname{Var}(X)'},
  {cat:'통계', code:'\\sim N(\\mu, \\sigma^{2})', desc:'정규분포를 따른다', tex:'X \\sim N(\\mu,\\sigma^{2})'},
  {cat:'통계', code:'{}_{n}P_{r}', desc:'순열', tex:'{}_{n}P_{r}'},
  {cat:'통계', code:'{}_{n}C_{r}', desc:'조합', tex:'{}_{n}C_{r}'},
  {cat:'통계', code:'▢!', desc:'팩토리얼', tex:'n!'},

  /* ── 서식·공백 ── */
  {cat:'서식', code:'\\,', desc:'좁은 공백', tex:'a\\,b'},
  {cat:'서식', code:'\\;', desc:'조금 넓은 공백', tex:'a\\;b'},
  {cat:'서식', code:'\\quad', desc:'넓은 공백', tex:'a\\quad b'},
  {cat:'서식', code:'\\qquad', desc:'아주 넓은 공백', tex:'a\\qquad b'},
  {cat:'서식', code:'\\\\', desc:'줄 바꿈 (여러 줄 수식 안에서)', tex:'\\begin{aligned} a \\\\ b \\end{aligned}'},
  {cat:'서식', code:'\\mathbf{▢}', desc:'굵게 (벡터·행렬)', tex:'\\mathbf{v}'},
  {cat:'서식', code:'\\mathrm{▢}', desc:'똑바로 (단위·상수)', tex:'\\mathrm{km}'},
  {cat:'서식', code:'\\mathcal{▢}', desc:'필기체 (집합족)', tex:'\\mathcal{F}'},
  {cat:'서식', code:'\\mathbb{▢}', desc:'칠판체 (수 집합)', tex:'\\mathbb{R}'},
  {cat:'서식', code:'\\color{red}{▢}', desc:'색 넣기', tex:'\\color{red}{x}'},
  {cat:'서식', code:'\\substack{▢ \\\\ ▢}', desc:'조건 두 줄 쌓기', tex:'\\sum_{\\substack{i=1 \\\\ i \\ne j}}'},
  {cat:'서식', code:'\\displaystyle', desc:'항상 큰 모양으로', tex:'\\displaystyle\\sum_{i=1}^{n}'},
];

/* ═══════════════════════════════════════════
   예제 모음
   ═══════════════════════════════════════════ */
const EXAMPLES = [
  {g:'고등·기초', t:'이차방정식 근의 공식', tex:'x = \\frac{-b \\pm \\sqrt{b^{2}-4ac}}{2a}'},
  {g:'고등·기초', t:'피타고라스 정리', tex:'a^{2} + b^{2} = c^{2}'},
  {g:'고등·기초', t:'등차수열의 합', tex:'S_{n} = \\frac{n(a_{1}+a_{n})}{2}'},
  {g:'고등·기초', t:'등비수열의 합', tex:'S_{n} = \\frac{a(1-r^{n})}{1-r} \\quad (r \\ne 1)'},
  {g:'고등·기초', t:'이항정리', tex:'(x+y)^{n} = \\sum_{k=0}^{n} \\binom{n}{k} x^{n-k} y^{k}'},
  {g:'고등·기초', t:'로그 성질', tex:'\\log_{a}(xy) = \\log_{a} x + \\log_{a} y'},

  {g:'미적분', t:'미분계수의 정의', tex:"f'(x) = \\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}"},
  {g:'미적분', t:'미적분의 기본정리', tex:'\\int_{a}^{b} f(x)\\,dx = F(b) - F(a)'},
  {g:'미적분', t:'부분적분', tex:'\\int u\\,dv = uv - \\int v\\,du'},
  {g:'미적분', t:'연쇄법칙', tex:'\\frac{dy}{dx} = \\frac{dy}{du} \\cdot \\frac{du}{dx}'},
  {g:'미적분', t:'테일러 급수', tex:'f(x) = \\sum_{n=0}^{\\infty} \\frac{f^{(n)}(a)}{n!}(x-a)^{n}'},
  {g:'미적분', t:'중요한 극한', tex:'\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1'},
  {g:'미적분', t:'e 의 정의', tex:'e = \\lim_{n \\to \\infty}\\left(1 + \\frac{1}{n}\\right)^{n}'},
  {g:'미적분', t:'편미분 (기울기)', tex:'\\nabla f = \\left( \\frac{\\partial f}{\\partial x}, \\frac{\\partial f}{\\partial y} \\right)'},
  {g:'미적분', t:'이중적분', tex:'\\iint_{D} f(x,y)\\,dA'},

  {g:'선형대수', t:'2×2 행렬', tex:'A = \\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}'},
  {g:'선형대수', t:'행렬식', tex:'\\det(A) = \\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix} = ad - bc'},
  {g:'선형대수', t:'역행렬', tex:'A^{-1} = \\frac{1}{ad-bc}\\begin{pmatrix} d & -b \\\\ -c & a \\end{pmatrix}'},
  {g:'선형대수', t:'고윳값 방정식', tex:'A\\mathbf{v} = \\lambda \\mathbf{v}'},
  {g:'선형대수', t:'일반 행렬 (점 표기)', tex:'\\begin{bmatrix} a_{11} & \\cdots & a_{1n} \\\\ \\vdots & \\ddots & \\vdots \\\\ a_{m1} & \\cdots & a_{mn} \\end{bmatrix}'},
  {g:'선형대수', t:'내적', tex:'\\mathbf{a} \\cdot \\mathbf{b} = \\sum_{i=1}^{n} a_{i} b_{i}'},
  {g:'선형대수', t:'벡터 크기', tex:'\\|\\mathbf{v}\\| = \\sqrt{v_{1}^{2} + v_{2}^{2} + v_{3}^{2}}'},

  {g:'통계·확률', t:'표본평균', tex:'\\bar{x} = \\frac{1}{n}\\sum_{i=1}^{n} x_{i}'},
  {g:'통계·확률', t:'표본분산', tex:'s^{2} = \\frac{1}{n-1}\\sum_{i=1}^{n}(x_{i} - \\bar{x})^{2}'},
  {g:'통계·확률', t:'정규분포 확률밀도함수', tex:'f(x) = \\frac{1}{\\sigma\\sqrt{2\\pi}} e^{-\\frac{(x-\\mu)^{2}}{2\\sigma^{2}}}'},
  {g:'통계·확률', t:'베이즈 정리', tex:'P(A \\mid B) = \\frac{P(B \\mid A)\\,P(A)}{P(B)}'},
  {g:'통계·확률', t:'이항분포', tex:'P(X=k) = \\binom{n}{k} p^{k}(1-p)^{n-k}'},
  {g:'통계·확률', t:'표준화 (z 점수)', tex:'z = \\frac{x - \\mu}{\\sigma}'},
  {g:'통계·확률', t:'신뢰구간', tex:'\\bar{x} \\pm z_{\\alpha/2} \\frac{\\sigma}{\\sqrt{n}}'},

  {g:'물리·공학', t:'뉴턴 제2법칙', tex:'\\vec{F} = m\\vec{a}'},
  {g:'물리·공학', t:'질량-에너지 등가', tex:'E = mc^{2}'},
  {g:'물리·공학', t:'만유인력', tex:'F = G\\frac{m_{1}m_{2}}{r^{2}}'},
  {g:'물리·공학', t:'감쇠 진동 방정식', tex:'m\\ddot{x} + c\\dot{x} + kx = 0'},
  {g:'물리·공학', t:'오일러 공식', tex:'e^{i\\theta} = \\cos\\theta + i\\sin\\theta'},
  {g:'물리·공학', t:'푸리에 변환', tex:'\\hat{f}(\\xi) = \\int_{-\\infty}^{\\infty} f(x)\\,e^{-2\\pi i x \\xi}\\,dx'},

  {g:'기타 서식', t:'경우 나누어 정의', tex:'|x| = \\begin{cases} x & (x \\ge 0) \\\\ -x & (x < 0) \\end{cases}'},
  {g:'기타 서식', t:'연립방정식', tex:'\\begin{cases} 2x + y = 5 \\\\ x - y = 1 \\end{cases}'},
  {g:'기타 서식', t:'여러 줄 정렬', tex:'\\begin{aligned} y &= (x+1)^{2} \\\\ &= x^{2} + 2x + 1 \\end{aligned}'},
  {g:'기타 서식', t:'단위 붙이기', tex:'v = 9.8\\,\\mathrm{m/s^{2}}'},
  {g:'기타 서식', t:'한글 섞어 쓰기', tex:'\\text{넓이} = \\pi r^{2}'},
];

/* ═══════════════════════════════════════════
   연습 문제 (쉬운 것부터)
   ═══════════════════════════════════════════ */
const QUIZ = [
  {tex:'x^{2}', hint:'위 첨자는 ^ 입니다. 한 글자라 중괄호는 있어도 없어도 됩니다.'},
  {tex:'a_{1}', hint:'아래 첨자는 _ 입니다.'},
  {tex:'x^{10}', hint:'두 글자 이상은 반드시 중괄호로 묶어야 합니다. x^10 이라고 쓰면 0이 내려옵니다.'},
  {tex:'\\frac{1}{2}', hint:'분수는 \\frac{분자}{분모} 입니다.'},
  {tex:'\\frac{a+b}{c}', hint:'분자가 여러 글자여도 통째로 중괄호 하나에 넣습니다.'},
  {tex:'\\sqrt{2}', hint:'제곱근은 \\sqrt{ } 입니다.'},
  {tex:'\\sqrt[3]{x}', hint:'n제곱근의 n 은 대괄호에 씁니다: \\sqrt[3]{ }'},
  {tex:'\\alpha + \\beta', hint:'그리스 문자는 이름 앞에 백슬래시를 붙입니다.'},
  {tex:'x \\le 5', hint:'≤ 는 \\le, ≥ 는 \\ge 입니다.'},
  {tex:'\\pi r^{2}', hint:'\\pi 뒤에 r 의 제곱입니다.'},
  {tex:'\\sin x', hint:'함수 이름에는 백슬래시를 붙여야 똑바로 섭니다.'},
  {tex:'\\log_{2} 8', hint:'로그의 밑은 아래첨자로 씁니다.'},
  {tex:'\\sum_{k=1}^{n} k', hint:'\\sum 뒤에 _{아래}^{위} 순서로 붙입니다.'},
  {tex:'\\int_{0}^{1} x\\,dx', hint:'\\int_{아래}^{위}, dx 앞의 \\, 는 얇은 공백입니다.'},
  {tex:'\\lim_{x \\to 0} f(x)', hint:'극한의 조건은 아래첨자에 넣고, → 는 \\to 입니다.'},
  {tex:'\\frac{dy}{dx}', hint:'도함수도 그냥 분수로 씁니다.'},
  {tex:'\\left( \\frac{a}{b} \\right)', hint:'분수를 감싸는 괄호는 \\left( 와 \\right) 로 늘립니다.'},
  {tex:'\\left| x - 1 \\right|', hint:'절댓값 기호는 | 이고, 늘리려면 \\left| \\right| 입니다.'},
  {tex:'\\vec{v}', hint:'벡터 화살표는 \\vec{ } 입니다.'},
  {tex:'\\bar{x}', hint:'평균 표시는 \\bar{ } 입니다.'},
  {tex:'x \\in \\mathbb{R}', hint:'∈ 는 \\in, 실수 집합은 \\mathbb{R} 입니다.'},
  {tex:'\\binom{n}{k}', hint:'이항계수는 \\binom{위}{아래} 입니다.'},
  {tex:'\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}', hint:'칸은 & 로, 줄은 \\\\ 로 나눕니다.'},
  {tex:'\\frac{-b \\pm \\sqrt{b^{2}-4ac}}{2a}', hint:'근의 공식입니다. ± 는 \\pm 이고, 루트 안이 분자 일부입니다.'},
];
